### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [ristodms/prj-rev-bwfs-dasmoto#1]
Overall exceeded expectations.  This project had the items I loved for in the first project.  Use of divs for each section.  Use of classes.  CSS is well organized and isn't overly repetitive.  

I do not have any issue to point so I like to mention a best practice you should get into the habit of doing. 
These projects are going to scale up in size, in the final 3-4 you css files are going to be between 300-400 lines.  I  would use comments for each section in the html to specific denote the topic and have matching comments in the css to make it easier to find it for that specific section.

Now as a challenge I like you to go to flexboxfroggy.com.  See how far you can go, in the later projects flexbox is used heavily and this will help prepare you for this.

**Comment by ristodms** [comment]
Hey!

Thanks, that was fun. Did grid garden as well.

I'll try to comment more in next project.
